version: '3.5'

services:
  backend:
    image: ${BACKEND_IMAGE}

    ports:
      - "${EXTERNAL_BACKEND_PORT}:${INTERNAL_BACKEND_PORT}"

    environment:
      DATABASE: ${DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      DATABASE_HOST: ${DOCKER_IP}
      DATABASE_PORT: ${EXTERNAL_DATABASE_PORT}

  frontend:
    image: ${FRONTEND_IMAGE}

    ports:
      - "${EXTERNAL_FRONTEND_PORT}:${INTERNAL_FRONTEND_PORT}"

  database:
    image: ${DATABASE_IMAGE}

    ports:
      - "${EXTERNAL_DATABASE_PORT}:${INTERNAL_DATABASE_PORT}"

    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}

    volumes:
      - gdg-datavolume:/var/lib/mysql

volumes:
  gdg-datavolume: